version: "3.7"
services:
#  catch-admin-os:
#    build: ./alpine
#    container_name: "catch-admin-os"
#    restart: always
#
#  catch-admin-db:
#    build: ./mysql
#    container_name: "catch-admin-db"
#    command: --default-authentication-plugin=mysql_native_password
#    restart: always
#    ports:
#      - "3306:3306"
#    volumes:
#      - ../config/mysql:/var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: 123456
#  catch-admin-redis:
#    build: ./redis
#    container_name: "catch-admin-redis"
#    command: redis-server --requirepass 7GS#kcKxob%Nhsk!
#    restart: always
#    ports:
#      - "6379:6379"
#    volumes:
#      - ../config/redis/conf:/usr/local/etc/redis
#      - ../config/redis/data:/data
#      - ../config/redis/logs:/logs
#  catch-admin-php:
#    build: ./php
#    container_name: "catch-admin-php"
#    restart: always
#    ports:
#      - "9000:9000"
#    volumes:
#      - ../catch-admin-backend:/var/www/html
#      - ../config/php/php.ini:/usr/local/etc/php/php.ini
#      - ../config/php/source.list.d:/etc/apt/sources.list.d
#    links:
#      - "catch-admin-db"
#      - "catch-admin-redis"
#  catch-admin-nginx:
#    build: ./nginx
#    container_name: "catch-admin-nginx"
#    restart: always
#    ports:
#      - "8000:8000"
#    links:
#      - "catch-admin-php"
#    volumes:
#      - ../catch-admin-frontend:/usr/share/nginx/html
#      - ../config/nginx:/etc/nginx
#      - ../config/logs/nginx.logs:/var/log/nginx
  catch-admin-node:
    build: ./node
    container_name: "catch-admin-node"
    command: npm i --registry https://registry.npm.taobao.org/
    command: npm run serve
    working_dir: /home/app
    restart: always
    ports:
      - "8001:8001"
#    links:
#      - "catch-admin-nginx"
    volumes:
      - ../catch-admin-frontend:/home/app
      - /home/app/node_modules
    environment:
      SERVER_PORT: 3001
      NODE_ENV: development
